### ISSUE TITLE
Thanks for your great job! Can you send a dataset download link to me？

### ISSUE THREAD

**Issue by lhcalibur** [pandamax/Parse_Curvelanes#2]

**Comment by sandeepnmenon** [comment]
Coming to this repo from https://github.com/koyeongmin/PINet_new/tree/master/TuSimple where it says I can download the Curvelanes dataset.
Can you share the dataset download link.
Thank you

**Comment by pandamax** [comment]
Sorry to reply you too late, please refer to [it](https://github.com/SoulmateB/CurveLanes) if it is available.
